### ISSUE TITLE
Using celocli, A user SBAT use the Validator Group address in the `from` and the `for` parameters  without errors

### ISSUE THREAD

**Issue by aaitor** [celo-org/celo-monorepo#1543]
### Expected Behavior

In the [Running a Validator doc page](https://github.com/celo-org/celo-monorepo/blob/alfajores/packages/docs/getting-started/running-a-validator.md) is specified a user should be able to use the validator group address to vote a validator group with that address.

So the following `celocli` command should work :

```
celocli validatorgroup:vote --from $CELO_VALIDATOR_GROUP_ADDRESS --for $CELO_VALIDATOR_GROUP_ADDRESS
```

### Current Behavior

Executing the above command you get the following error:

```
$ celocli validatorgroup:vote --from $CELO_VALIDATOR_GROUP_ADDRESS --for $CELO_VALIDATOR_GROUP_ADDRESS

Sending Transaction: vote... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (~/.n/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.n/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/.n/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.n/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.n/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.n/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.n/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.n/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)

```

**Comment by nambrot** [comment]
Closing this assuming as we have had validators been able to do this (and i haven't really had the time to look into this)
