### ISSUE TITLE
Users should be able to reference the right balances on blockscout

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#1912]
### Expected Behavior

They should be the same

### Current Behavior

for `0x0456e7B4B6A7E25f167f4EBEB17B7268E36af4F8` and `7059f5038a97cb70f37c73fadae11b83dca982a8` the balances fetched from RPC are different than the values from blockscout. They are my validator and validator group so these are my rewards

on baklavastaging

**Comment by mrsmkl** [comment]
What I have been able to find out so far: all the token transfers are stored, but updating the current balances stopped working after block 13140.

**Comment by mrsmkl** [comment]
So looks like the error that showed in the logs caused it
```
iex(1)> 2019-11-26T01:42:55.126 [error] Task #PID<0.3879.5> started from Indexer.Block.Realtime.Fetcher terminating
** (Postgrex.Error) ERROR 22023 (invalid_parameter_value) payload string too long
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
    (explorer) lib/explorer/chain/events/publisher.ex:13: anonymous fn/3 in Explorer.Chain.Events.Publisher.broadcast/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (explorer) lib/explorer/chain/events/publisher.ex:12: Explorer.Chain.Events.Publisher.broadcast/2
    (explorer) lib/explorer/chain/import.ex:128: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/block/realtime/fetcher.ex:209: Indexer.Block.Realtime.Fetcher.import/2
    (indexer) lib/indexer/block/fetcher.ex:201: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:292: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [13346, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://10.138.0.7:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```
I'll try to find a way to just ignore it first, and then try to find out if we can get rid of it.
