### ISSUE TITLE
[cli] Validators SBATS to see readable error message when trying to vote with more gold than they have locked

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#1981]
### Expected Behavior

Error message should be shown.

### Current Behavior

```
cli$ ./bin/run election:vote --from $CELO_VALIDATOR_ADDRESS --for 0xEF65BBCF2Dbc1411E15081cb2f96C904bc797EB1 --value 24000000000000000000000
Running Checks:
   ✔  0a82796a9d665d0e93361c45fd7b0093e55cb5c1 is Signer or Account
   ✔  0xEF65BBCF2Dbc1411E15081cb2f96C904bc797EB1 is ValidatorGroup
Sending Transaction: vote... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (~/celo-monorepo/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/celo-monorepo/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/celo-monorepo/packages/cli/src/utils/eth-debug-provider.ts:17:13)
    at XMLHttpRequest.request.onreadystatechange (~/celo-monorepo/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/celo-monorepo/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```

**Comment by martinvol** [comment]
It'd be also nice to have a `--all` flag, to just vote with all the locked gold.

I think this requirements are also needed for the `lock` command.
