### ISSUE TITLE
CLI command election:list does not work

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#2076]
### Expected Behavior

Command works

### Current Behavior

```.➜  cli git:(master) ✗ ./bin/run election:list
Fetching validator group vote totals... !
Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (~/celo/celo-monorepo/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (~/celo/celo-monorepo/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (~/celo/celo-monorepo/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (~/celo/celo-monorepo/node_modules/web3-eth-contract/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (~/celo/celo-monorepo/node_modules/web3-eth-contract/node_modules/web3-core-method/src/index.js:473:33)
    at ~/celo/celo-monorepo/node_modules/web3-core-requestmanager/src/index.js:147:9
    at callbackDecorator (~/celo/celo-monorepo/packages/cli/src/utils/eth-debug-provider.ts:17:13)
    at XMLHttpRequest.request.onreadystatechange (~/celo/celo-monorepo/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/celo/celo-monorepo/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/celo/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/celo/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/celo/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:311:39)```

**Comment by hqueue** [comment]
Still reproduced with the latest version of celocli for TGCSO Phase 1.1

```
$ celocli --version
@celo/celocli/0.0.32-beta3 linux-x64 node-v10.17.0
$ celocli election:list
Fetching validator group vote totals... !
Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-method/src/index.js:473:33)
    at ~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:147:9
    at callbackDecorator (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```

**Comment by asaj** [comment]
This has been fixed by https://github.com/celo-org/celo-monorepo/pull/2216
