### ISSUE TITLE
Governance e2e tests fail sometimes on epoch score and reward

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#2220]
### Expected Behavior

`end-to-end-geth-governance-test` goes through

### Current Behavior

`end-to-end-geth-governance-test` fails with an error (see below). In circle ci it does not fail always. Locally it always fails for me now.

https://circleci.com/gh/celo-org/celo-monorepo/94321?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
  9 passing (10m)
  2 failing

  1) governance tests
       when the validator set is changing
         should update the validator scores at the end of each epoch:
     AssertionError: expected 0 to almost equal 100000000000000000000000 +/- 5000000000000
      at Object.assertAlmostEqual (src/e2e-tests/utils.ts:44:16)
      at Context.<anonymous> (src/e2e-tests/governance_tests.ts:481:29)
      at Generator.next (<anonymous>)
      at fulfilled (src/e2e-tests/governance_tests.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) governance tests
       when the validator set is changing
         should distribute epoch rewards at the end of each epoch:
     AssertionError: expected 0 to almost equal 89165304570705000000 +/- 5000000000000
      at Object.assertAlmostEqual (src/e2e-tests/utils.ts:44:16)
      at Context.<anonymous> (src/e2e-tests/governance_tests.ts:557:29)
      at Generator.next (<anonymous>)
      at fulfilled (src/e2e-tests/governance_tests.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by H34D** [comment]
I tracked this issue down to be related to this change: https://github.com/celo-org/celo-monorepo/commit/5173792786210d51b9963c48e7e6a0e20e5e7f3a

maybe the e2e tests need to be updated?

**Comment by H34D** [comment]
i implicitly worked on this today, it looks like that this happens on networks with validators running without the `--istanbul.blockperiod` flag. I added this to my tests and the issue disappeared.
