### ISSUE TITLE
attestations: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by SlavaMo** [celo-org/celo-monorepo#2477]
### Expected Behavior
```
POST /attestations
Sent sms
attestationRequest...
statusCode...
```
### Current Behavior
```
*2020-01-18T17:37:18.118Z attestation-service[60] INFO:  POST celo.slavamo.tk/attestations
   req_id: "9c05fbbf-c55f-49b0-a364-2e317f92fb6b"
 2020-01-18T17:37:31.365Z attestation-service[60] INFO:  Returned values aren't valid, did it run Out of Gas?
   err: Error: Returned values aren't valid, did it run Out of Gas?
       at ABICoder.decodeParameters (/celo-monorepo/node_modules/web3-eth-abi/src/index.js:226:15)
       at Contract._decodeMethodReturn (/celo-monorepo/node_modules/web3-eth-contract/src/index.js:465:22)
       at Method.outputFormatter (/celo-monorepo/node_modules/web3-eth-contract/src/index.js:818:46)
       at Method.formatOutput (/celo-monorepo/node_modules/web3-core-method/src/index.js:163:54)
       at sendTxCallback (/celo-monorepo/node_modules/web3-core-method/src/index.js:473:33)
       at /celo-monorepo/node_modules/web3-core-requestmanager/src/index.js:147:9
       at XMLHttpRequest.request.onreadystatechange (/celo-monorepo/node_modules/web3-providers-http/src/index.js:96:13)
       at XMLHttpRequestEventTarget.dispatchEvent (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
       at XMLHttpRequest._setReadyState (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
       at XMLHttpRequest._onHttpResponseEnd (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
       at IncomingMessage.<anonymous> (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
       at IncomingMessage.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1143:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
   req_id: "9c05fbbf-c55f-49b0-a364-2e317f92fb6b"
   attestationRequest: {"account":"0x5A0747CFAFeAD6366073FFa65E9A53238aeA7B9A","phoneNumber":"+4915735989761","issuer":"0xe49515934d5eB7e8A2DF1F6b00a819de9938f2C6"}
 2020-01-18T17:37:31.532Z attestation-service[60] INFO:  
   req_id: "9c05fbbf-c55f-49b0-a364-2e317f92fb6b"
   res: {"statusCode":422,"header":"HTTP/1.1 422 Unprocessable Entity\r\nX-Powered-By: Express\r\nX-Request-Id: 9c05fbbf-c55f-49b0-a364-2e317f92fb6b\r\nContent-Type: application/json; charset=utf-8\r\nConte..
 2020-01-18T17:45:18.698Z attestation-service[60] INFO:  GET /
   req_id: "c791d1af-f00b-493c-ad02-242968d4f512"
*2020-01-18T17:49:27.501Z attestation-service[60] INFO:  POST celo.slavamo.tk/attestations
   req_id: "278305eb-e289-4f6a-b499-3d078c64f89e"
 2020-01-18T17:49:35.342Z attestation-service[60] INFO:  No incomplete attestation found
   err: Error: No incomplete attestation found
       at AttestationRequestHandler.<anonymous> (./src/requestHandlers/attestation.ts:114:13)
       at step (./lib/requestHandlers/attestation.js:33:23)
       at Object.next (./lib/requestHandlers/attestation.js:14:53)
       at fulfilled (./lib/requestHandlers/attestation.js:5:58)
       at process._tickCallback (internal/process/next_tick.js:68:7)
   req_id: "278305eb-e289-4f6a-b499-3d078c64f89e"
   attestationRequest: {"account":"0x5A0747CFAFeAD6366073FFa65E9A53238aeA7B9A","phoneNumber":"+4915735989761","issuer":"0xe49515934d5eB7e8A2DF1F6b00a819de9938f2C6"}
 2020-01-18T17:49:35.392Z attestation-service[60] INFO:  
   req_id: "278305eb-e289-4f6a-b499-3d078c64f89e"
   res: {"statusCode":422,"header":"HTTP/1.1 422 Unprocessable Entity\r\nX-Powered-By: Express\r\nX-Request-Id: 278305eb-e289-4f6a-b499-3d078c64f89e\r\nContent-Type: application/json; charset=utf-8\r\nConte..
 2020-01-18T18:03:53.501Z attestation-service[60] INFO:  GET 176.58.96.85/
   req_id: "38d32db2-136b-4b73-b2db-0429f0ff5360"
 2020-01-18T18:03:54.486Z attestation-service[60] INFO:  GET 176.58.96.85/robots.txt
   req_id: "bbfe2094-ab78-4578-8ae8-8328868d9d6d"
 2020-01-18T18:03:55.750Z attestation-service[60] INFO:  POST 176.58.96.85/Admin55603ab0/Login.php
   req_id: "5cde8681-f630-46dd-b274-de26ba7cf14d"
*2020-01-18T18:03:57.016Z attestation-service[60] INFO:  POST celo.slavamo.tk/attestations
   req_id: "be3c69b5-4782-4050-81ee-d325ad9f8bd8"
 2020-01-18T18:04:04.024Z attestation-service[60] INFO:  No incomplete attestation found
   err: Error: No incomplete attestation found
       at AttestationRequestHandler.<anonymous> (./src/requestHandlers/attestation.ts:114:13)
       at step (./lib/requestHandlers/attestation.js:33:23)
       at Object.next (./lib/requestHandlers/attestation.js:14:53)
       at fulfilled (./lib/requestHandlers/attestation.js:5:58)
       at process._tickCallback (internal/process/next_tick.js:68:7)
   req_id: "be3c69b5-4782-4050-81ee-d325ad9f8bd8"
   attestationRequest: {"account":"0x5A0747CFAFeAD6366073FFa65E9A53238aeA7B9A","phoneNumber":"+4915735989761","issuer":"0xe49515934d5eB7e8A2DF1F6b00a819de9938f2C6"}
 2020-01-18T18:04:04.153Z attestation-service[60] INFO:  
   req_id: "be3c69b5-4782-4050-81ee-d325ad9f8bd8"
   res: {"statusCode":422,"header":"HTTP/1.1 422 Unprocessable Entity\r\nX-Powered-By: Express\r\nX-Request-Id: be3c69b5-4782-4050-81ee-d325ad9f8bd8\r\nContent-Type: application/json; charset=utf-8\r\nConte..
 2020-01-18T18:19:49.977Z attestation-service[60] INFO:  GET 176.58.96.85:80/
   req_id: "9a03d09b-d32f-4944-9b9a-aee7a484dd48"
*2020-01-18T18:19:57.287Z attestation-service[60] INFO:  POST celo.slavamo.tk/attestations
   req_id: "10469c14-8557-4f5f-bf98-595c69651d10"
 2020-01-18T18:19:59.958Z attestation-service[60] INFO:  No incomplete attestation found
   err: Error: No incomplete attestation found
       at AttestationRequestHandler.<anonymous> (./src/requestHandlers/attestation.ts:114:13)
       at step (./lib/requestHandlers/attestation.js:33:23)
       at Object.next (./lib/requestHandlers/attestation.js:14:53)
       at fulfilled (./lib/requestHandlers/attestation.js:5:58)
       at process._tickCallback (internal/process/next_tick.js:68:7)
   req_id: "10469c14-8557-4f5f-bf98-595c69651d10"
   attestationRequest: {"account":"0x5A0747CFAFeAD6366073FFa65E9A53238aeA7B9A","phoneNumber":"+4915735989761","issuer":"0xe49515934d5eB7e8A2DF1F6b00a819de9938f2C6"}
 2020-01-18T18:20:00.091Z attestation-service[60] INFO:  
   req_id: "10469c14-8557-4f5f-bf98-595c69651d10"
   res: {"statusCode":422,"header":"HTTP/1.1 422 Unprocessable Entity\r\nX-Powered-By: Express\r\nX-Request-Id: 10469c14-8557-4f5f-bf98-595c69651d10\r\nContent-Type: application/json; charset=utf-8\r\nConte..
 2020-01-18T18:25:39.941Z attestation-service[60] INFO:  GET 176.58.96.85:80/
   req_id: "7a9302a3-fda5-4fda-bdc1-1f87fbcefa72"
*2020-01-18T18:35:09.351Z attestation-service[60] INFO:  POST celo.slavamo.tk/attestations
   req_id: "f8f5307e-2b74-42ca-ad74-f5a2758495cc"
 2020-01-18T18:35:39.544Z attestation-service[60] INFO:  Returned values aren't valid, did it run Out of Gas?
   err: Error: Returned values aren't valid, did it run Out of Gas?
       at ABICoder.decodeParameters (/celo-monorepo/node_modules/web3-eth-abi/src/index.js:226:15)
       at Contract._decodeMethodReturn (/celo-monorepo/node_modules/web3-eth-contract/src/index.js:465:22)
       at Method.outputFormatter (/celo-monorepo/node_modules/web3-eth-contract/src/index.js:818:46)
       at Method.formatOutput (/celo-monorepo/node_modules/web3-core-method/src/index.js:163:54)
       at sendTxCallback (/celo-monorepo/node_modules/web3-core-method/src/index.js:473:33)
       at /celo-monorepo/node_modules/web3-core-requestmanager/src/index.js:147:9
       at XMLHttpRequest.request.onreadystatechange (/celo-monorepo/node_modules/web3-providers-http/src/index.js:96:13)
       at XMLHttpRequestEventTarget.dispatchEvent (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
       at XMLHttpRequest._setReadyState (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
       at XMLHttpRequest._onHttpResponseEnd (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
       at IncomingMessage.<anonymous> (/celo-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
       at IncomingMessage.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1143:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
   req_id: "f8f5307e-2b74-42ca-ad74-f5a2758495cc"
   attestationRequest: {"account":"0x5A0747CFAFeAD6366073FFa65E9A53238aeA7B9A","phoneNumber":"+4915735989761","issuer":"0xe49515934d5eB7e8A2DF1F6b00a819de9938f2C6"}
 2020-01-18T18:35:39.589Z attestation-service[60] INFO:  
   req_id: "f8f5307e-2b74-42ca-ad74-f5a2758495cc"
   res: {"statusCode":422,"header":"HTTP/1.1 422 Unprocessable Entity\r\nX-Powered-By: Express\r\nX-Request-Id: f8f5307e-2b74-42ca-ad74-f5a2758495cc\r\nContent-Type: application/json; charset=utf-8\r\nConte.```
```

twilio does not even show any attempt to send sms and before it worked good.

**Comment by SlavaMo** [comment]
After posting this issue i have received 5 attestations and all went OK without me changing anything in my attestations-node/twilio configs. Still have very bad score of 8/11 = 72%

**Comment by nategraf** [comment]
@nambrot could this be related to the attestation contract like we discussed earlier?
