### ISSUE TITLE
Validator - Run Election - Error

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#26]
### Expected Behavior

When running this command for Validator - Run Election

```
$ celocli validator:register --id <VALIDATOR_ID_OF_YOUR_CHOICE> --name <VALIDATOR_NAME_OF_YOUR_CHOICE> --url <VALIDATOR_URL_OF_YOUR_CHOICE> --from $CELO_VALIDATOR_ADDRESS --noticePeriod 5184000 --publicKey 0x`openssl rand -hex 64` 
```

### Current Behavior

Getting errors when Running for Election

```
Sending Transaction: registerValidator... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (/usr/local/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /usr/local/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (/usr/local/lib/node_modules/@celo/celocli/lib/utils/eth-debug-provider.js:17:13)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
```

**Comment by clrblmt** [comment]
https://forum.celo.org/t/setting-up-a-validator-faq/90
