### ISSUE TITLE
Celostats-server error: Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by jcortejoso** [celo-org/celo-monorepo#3271]
### Current Behavior
Celostats throws the next error and the process dies:

```
2020-04-02 09:20:48.067 [API] [CON] Node Open: ::ffff:10.8.6.32:39542 (qkn-GGT4J06151kqLauIO)
2020-04-02 09:20:48.079 [API] [CON] Hello 'rc0-validators-49' (qkn-GGT4J06151kqLauIO)
2020-04-02 09:20:48.081 [API] [CON] Node 'rc0-validators-49' (qkn-GGT4J06151kqLauIO) Connected
/celostats-server/dist/server/Controller.js:90
                    console.info('API', 'BLK', 'Block:', stats.block['number'], 'TotalDifficulty:', stats.block['totalDifficulty'], 'from:', stats.id, 'ip:', ip);
                                                                    ^
TypeError: Cannot read property 'number' of undefined
    at Controller.handleNodeBlock (/celostats-server/dist/server/Controller.js:90:69)
    at Sparky.<anonymous> (/celostats-server/dist/server/server/server.js:105:37)
    at Sparky.emit (events.js:311:20)
    at Sparky.incoming (/celostats-server/node_modules/primus-emit/index.js:72:44)
    at transform (/celostats-server/node_modules/primus/spark.js:312:33)
    at Sparky.transforms (/celostats-server/node_modules/primus/spark.js:330:4)
    at decoding (/celostats-server/node_modules/primus/spark.js:215:13)
    at Sparky.decoder (/celostats-server/node_modules/primus/parsers/json.js:34:3)
    at Sparky.message (/celostats-server/node_modules/primus/spark.js:200:20)
    at Sparky.emit (events.js:311:20)
    at Sparky.emitter [as emit] (/celostats-server/node_modules/primus-emit/index.js:82:19)
    at WebSocket.emitter (/celostats-server/node_modules/emits/index.js:26:22)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/celostats-server/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/celostats-server/node_modules/ws/lib/receiver.js:423:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @celo/celostats-server@0.2.0 start: `node ./dist/server/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @celo/celostats-server@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-02T09_20_48_124Z-debug.log
```

**Comment by H34D** [comment]
it only happens under high load, its on the list to be fixed but hard to reproduce.

**Comment by H34D** [comment]
potential fixed here: https://github.com/celo-org/celostats-server/commit/879c2abcd5acbaf7abc537e72d3b218a7a9d01ac

when happening again, please reopen
