### ISSUE TITLE
ContractKit Azure HSM: Unable to generate recovery key from signature

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#3498]
### Expected Behavior

No errors when signing with an Azure HSM

### Current Behavior

I found this error when using an Azure HSM via contractkit:

```
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to generate recovery key from signature.
    at Function.AzureKeyVaultClient.recoverKeyIndex (/celo-oracle/node_modules/@celo/contractkit/lib/wallets/signers/azure-key-vault-client.js:257:15)
    at AzureKeyVaultClient.<anonymous> (/celo-oracle/node_modules/@celo/contractkit/lib/wallets/signers/azure-key-vault-client.js:202:61)
    at step (/celo-oracle/node_modules/@celo/contractkit/lib/wallets/signers/azure-key-vault-client.js:33:23)
    at Object.next (/celo-oracle/node_modules/@celo/contractkit/lib/wallets/signers/azure-key-vault-client.js:14:53)
    at fulfilled (/celo-oracle/node_modules/@celo/contractkit/lib/wallets/signers/azure-key-vault-client.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 164)
```

At the moment, @codyborn and I haven't been able to reproduce it but he has seen it as well

**Comment by zviadm** [comment]
I also hit this same issue. I am able to repro it, but it requires ~20-30 tries.
smallest repro is to setup `kit` with azure HSM wallet, and just run 'generateProofOfKeyPossession' in a loop

```
const wallet = new AzureHSMWallet('vault name')
await wallet.init()
const kit = newKit(uri, wallet)
const addr = await wallet.getAddressFromKeyName('key name')
const accounts = await kit.contracts.getAccounts()

for (let i = 0; i < 100; i++) {
  console.log("try", i)
  await accounts.generateProofOfKeyPossession("0x4d82BfC8823a4F3AF82B0AdE52ff3e2d74A04757", addr)
  await new Promise(resolve => setTimeout(resolve, 5000));
}
```

it will hit an error after some number of tries.

**Comment by zviadm** [comment]
I have enabled debugging too and error looks like:
```
try 20
  kit:wallet:akv-client Canonicalizing signature +5s
(node:84728) UnhandledPromiseRejectionWarning: Error: Unable to generate recovery key from signature.
    at Function.AzureKeyVaultClient.recoverKeyIndex (/Users/zviad/src/celovote/api/node_modules/@celo/contractkit/src/utils/azure-key-vault-client.ts:168:11)
    at AzureKeyVaultClient.<anonymous> (/Users/zviad/src/celovote/api/node_modules/@celo/contractkit/src/utils/azure-key-vault-client.ts:109:47)
    at step (/Users/zviad/src/celovote/api/node_modules/@celo/contractkit/lib/utils/azure-key-vault-client.js:33:23)
    at Object.next (/Users/zviad/src/celovote/api/node_modules/@celo/contractkit/lib/utils/azure-key-vault-client.js:14:53)
    at fulfilled (/Users/zviad/src/celovote/api/node_modules/@celo/contractkit/lib/utils/azure-key-vault-client.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:84728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

There might be some edgecase when canonicalizing is happening where it is incorrect

**Comment by zviadm** [comment]
Digging a little deeper I added some more printouts, and actual error that is silently ignore in try/catch is: "Expected signature to be an Uint8Array with length 64".

So my current suspicion is that mistake is in 'bigNumberToBuffer' function: https://github.com/celo-org/celo-monorepo/blob/11814bdb3b44bddb3c19a9ec0f439ad45e86b6bc/packages/contractkit/src/utils/azure-key-vault-client.ts#L195

if the big number is smaller than 0x4000000...... , then length of the buffer will be incorrect because it will not get zero padded correctly.
