### ISSUE TITLE
CLI tests fail locally

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#3573]
### Expected Behavior

Tests successfully run.

### Current Behavior

All tests fail with a similar exception:

 ```
FAIL src/commands/validator/register.test.ts
  Test suite failed to run

    dlopen(/Users/codyborn/repos/monorepo_celo/packages/cli/node_modules/usb/build/Release/usb_bindings.node, 1): no suitable image found.  Did find:
    	/Users/codyborn/repos/monorepo_celo/packages/cli/node_modules/usb/build/Release/usb_bindings.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    	/Users/codyborn/repos/monorepo_celo/packages/cli/node_modules/usb/build/Release/usb_bindings.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:770:29)
      at bindings (node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (node_modules/usb/usb.js:1:57)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/src/listenDevices.js:6:1)

Test Suites: 15 failed, 15 total
```
Repro Steps
1. Navigate to the contractkit directory 
2. `yarn`
3. `yarn build`
4. `yarn test:reset`
5. `yarn test`

Note that the tests in CircleCI do not reproduce this failure.  Both @gastonponti and I are hitting this locally.

**Comment by joe-bowman** [comment]
I get these same issues attempting to run `celocli` after installing:

```
Error: Could not locate the bindings file. Tried:
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/build/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/build/Debug/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/build/Release/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/out/Debug/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/Debug/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/out/Release/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/Release/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/build/default/usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/compiled/10.19.0/linux/x64/usb_bi
    ndings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/addon-build/release/install-root/
    usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/addon-build/debug/install-root/us
    b_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/addon-build/default/install-root/
    usb_bindings.node
     → /usr/local/lib/node_modules/@celo/celocli/node_modules/usb/lib/binding/node-v64-linux-x64/us
    b_bindings.node
```

**Comment by eelanagaraj** [comment]
Duplicate (precursor) of issue #6778 which is currently blocked. Closing this issue, check that other issue for progress, thanks!
