### ISSUE TITLE
Can't revoke last vote, if there are no other groups that account is voting for

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#3607]
### Expected Behavior

Revoking to work just fine.

### Current Behavior

```
$ celocli election:show --voter 0x59186b71b33f4d96ec525e9ee21a8cf989d5ace7
Failed to initialize libusb.
Running Checks:
   ✔  0x59186b71b33f4d96ec525e9ee21a8cf989d5ace7 is a registered Account 
address: 0x59186b71b33f4d96ec525e9ee21a8cf989d5ace7
votes: 
  0: 
    group: 0x59186b71b33F4d96eC525e9EE21A8cF989d5acE7
    pending: 0 
    active: 1 
```

```
$ celocli election:revoke --from 0xBC4A747C4d347B0E555872aBF9048dB8d0D7AC45 --for 0x59186b71b33f4d96ec525e9ee21a8cf989d5ace7 --value 1
Failed to initialize libusb.
Running Checks:
   ✔  0xBC4A747C4d347B0E555872aBF9048dB8d0D7AC45 is Signer or registered Account 
   ✔  0x59186b71b33f4d96ec525e9ee21a8cf989d5ace7 is ValidatorGroup 
Sending Transaction: revoke... !
Error: Gas estimation failed: Bad index
    at ContractKit.<anonymous> (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/kit.js:383:31)
    at step (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/kit.js:44:23)
    at Object.throw (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/kit.js:25:53)
    at rejected (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/kit.js:17:65)```

**Comment by zviadm** [comment]
I think i figured out what the bug is in the contract:
https://github.com/celo-org/celo-monorepo/blob/baklava/packages/protocol/contracts/governance/Election.sol#L795

deleteElement helper is getting called both from decremnt votes function AND also from revokeActive function. 
So first call removes the element, thus second one throws bad index error. 

I am guessing this means, revoking full amount of votes for a group will not work even if you have voted for other groups.

**Comment by zviadm** [comment]
Looks like revoking last vote doesn't work even if there are other groups voted for. So I am guessing somehow there is a bug in "deleteElement" function here :
https://github.com/celo-org/celo-monorepo/blob/baklava/packages/protocol/contracts/governance/Election.sol#L795

**Comment by zviadm** [comment]
Looks like this is just ContractKit bug. Revoke vote calls: https://github.com/celo-org/celo-monorepo/blob/d0b373a62d05d28c33373b43367dcb158efc1554/packages/contractkit/src/wrappers/Election.ts#L340

don't transform group address into mixed case version, thus .indexOf(group) can return -1 and cause an error when transaction is sent. Thanks @asaj for debugging.
