### ISSUE TITLE
CLI error in  account:claim-domain for @celo/celocli/0.0.47

### ISSUE THREAD

**Issue by hqueue** [celo-org/celo-monorepo#3646]
### Expected Behavior

No error.

### Current Behavior
With the latest version `@celo/celocli/0.0.47`, there is an error `account:claim-domain`
```
$ celocli account:claim-domain ./group_metadata.json --domain example.com --from $CELO_VALIDATOR_GROUP_SIGNER_ADDRESS
TypeError: Cannot read property 'name' of undefined
    at Object.exports.array (~/.nvm/versions/node/v10.20.1/lib/node_modules/@celo/celocli/node_modules/io-ts/lib/index.js:438:52)
    at Object.<anonymous> (~/.nvm/versions/node/v10.20.1/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/identity/metadata.js:66:15)
    at Object.<anonymous> (~/.nvm/versions/node/v10.20.1/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/identity/claims/keybase.js:48:18)
```

It works without problem in `@celo/celocli/0.0.46`

Reported at discord channel https://discordapp.com/channels/600834479145353243/704804037639405649/704935181924171806

**Comment by eelanagaraj** [comment]
Looks like it was closed with @celo/celocli/0.0.48, per confirmations later in the [Discord thread](https://discord.com/channels/600834479145353243/704804037639405649/707957515094196244)
