### ISSUE TITLE
testing flakey test tracking: ROOT_DESCRIBE_BLOCK -> tryObtainValueWithRetries() -> should fail sometimes null

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#4240]
Error: expect(<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#A00">received<span style="color:#FFF">).<span style="font-weight:normal;text-decoration:none;font-style:normal">toBeGreaterThan(<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#0A0">expected<span style="color:#FFF">)<span style="font-weight:normal;text-decoration:none;font-style:normal">

Expected: > <span style="color:#0A0">1<span style="color:#FFF">
Received:   <span style="color:#A00">0<span style="color:#FFF">
    at /Users/alec/celo/celo-monorepo/packages/utils/src/task.test.ts:249:15
    at step (/Users/alec/celo/celo-monorepo/packages/utils/src/task.test.ts:33:23)
    at Object.next (/Users/alec/celo/celo-monorepo/packages/utils/src/task.test.ts:14:53)
    at /Users/alec/celo/celo-monorepo/packages/utils/src/task.test.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alec/celo/celo-monorepo/packages/utils/src/task.test.ts:4:12)
    at Object.<anonymous> (/Users/alec/celo/celo-monorepo/packages/utils/src/task.test.ts:247:33)
    at Promise (/Users/alec/celo/celo-monorepo/node_modules/jest-circus/build/utils.js:230:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/alec/celo/celo-monorepo/node_modules/jest-circus/build/utils.js:170:10)</span></span></span></span></span></span></span></span></span></span></span></span>

**Comment by alecps** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```
