### ISSUE TITLE
Validator - Run Election - Error

### ISSUE THREAD

**Issue by pkrasam** [celo-org/celo-monorepo#44]
### Expected Behavior

When running this command for Validator - Run Election

```
$ celocli validator:register --id <VALIDATOR_ID_OF_YOUR_CHOICE> --name <VALIDATOR_NAME_OF_YOUR_CHOICE> --url <VALIDATOR_URL_OF_YOUR_CHOICE> --from $CELO_VALIDATOR_ADDRESS --noticePeriod 5184000 --publicKey 0x`openssl rand -hex 64` 
```

### Current Behavior

Getting errors when Running for Election

```
Sending Transaction: registerValidator... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (/usr/local/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /usr/local/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (/usr/local/lib/node_modules/@celo/celocli/lib/utils/eth-debug-provider.js:17:13)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
```

**Comment by asaj** [comment]
Thanks for raising this issue!

I'm assuming that you were able to execute all previous steps, including registering your bonded deposits accounts, making bonded deposits, and registering your validator group?

Did you substitute other values for `id`, `name`, and `url`?

**Comment by mattharrop** [comment]
I have seen a variant of issue as well.  I have set up two nodes.  

On the validator node I did not have any problems.   I was able to register the group and the validator, and vote for the group with both accounts as per the tutorial.

I tried to vote for my validator group with a local account on a second full node that is not a validator.  

```
mattharrop@celo-alfajores-node:~$ celocli validatorgroup:vote --for=0x164FCd343912749498Acc546073ef2344CdEe35D --from=0xdcb37537de5a2248b31cfddaeb4e398200dcc3c9
Sending Transaction: vote... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/lib/utils/eth-debug-provider.js:17:13)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.16.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
```

In order to confirm that I was able to use this account, and that the issue is specific to voting, I tested and was able to send a payment using this account, the tx hash is `0xc6c8a889d11891c54a17f8b61e7cc9a449b115bbd26afff206c43b637c2ec7b3`.
