### ISSUE TITLE
error running account:unlock with celocli@0.0.9 

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#561]
```
tim@Tims-MacBook-Pro:~/staging-test$ celocli account:unlock --account $CELO_VALIDATOR_GROUP_ADDRESS --password ""
(node:74751) Warning: Mismatched version in @celo/celocli plugin manifest. Expected: 0.0.9 Received: 0.0.6
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
(node:74751) [MODULE_NOT_FOUND] Error Plugin: @celo/celocli: Cannot find module 'globby'
module: @oclif/config@1.13.2
task: not loading commands, globby not found
plugin: @celo/celocli
root: /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli
See more details with DEBUG=*
 ›   Error: command account:unlock not found
tim@Tims-MacBook-Pro:~/staging-test$ DEBUG=* celocli account:unlock --account $CELO_VALIDATOR_GROUP_ADDRESS --password ""
  @oclif/config reading core plugin /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli +0ms
  @oclif/config loadJSON /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/package.json +0ms
  @oclif/config loadJSON /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/oclif.manifest.json +2ms
  @oclif/config reading user plugins pjson /Users/tim/.local/share/@celo/celocli/package.json +0ms
  @oclif/config loadJSON /Users/tim/.local/share/@celo/celocli/package.json +196ms
(node:74768) Warning: Mismatched version in @celo/celocli plugin manifest. Expected: 0.0.9 Received: 0.0.6
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
Warning: Mismatched version in @celo/celocli plugin manifest. Expected: 0.0.9 Received: 0.0.6
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
    at readManifest (/Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/config/lib/plugin.js:126:29)
    at <anonymous>
(node:74768) [MODULE_NOT_FOUND] Error Plugin: @celo/celocli: Cannot find module 'globby'
module: @oclif/config@1.13.2
task: not loading commands, globby not found
plugin: @celo/celocli
root: /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli
See more details with DEBUG=*
Error Plugin: @celo/celocli: Cannot find module 'globby'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Plugin.get commandIDs [as commandIDs] (/Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/config/lib/plugin.js:64:40)
    at Plugin._manifest (/Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/config/lib/plugin.js:151:28)
    at <anonymous>
module: @oclif/config@1.13.2
task: not loading commands, globby not found
plugin: @celo/celocli
root: /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli
See more details with DEBUG=*
  @oclif/config loading plugins [ '@oclif/plugin-help' ] +1ms
  @oclif/config reading core plugin /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/plugin-help/package.json +2ms
  @oclif/config loadJSON /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-help using manifest from /Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +2ms
  @oclif/config start init hook +1ms
  @oclif/config init hook done +0ms
  celocli init version: @oclif/command@1.5.18 argv: [ 'account:unlock', '--account', '--password', '' ] +0ms
  @oclif/config runCommand account:unlock [ '--account', '--password', '' ] +3ms
  @oclif/config start command_not_found hook +1ms
  @oclif/config command_not_found hook done +0ms
Error: command account:unlock not found
    at Config.runCommand (/Users/tim/.nvm/versions/node/v8.16.0/lib/node_modules/@celo/celocli/node_modules/@oclif/config/lib/config.js:147:19)
    at <anonymous>
```

**Comment by ashishb** [comment]
A new package has been deployed. https://github.com/celo-org/celo-monorepo/pull/446 contains the fix.
