### ISSUE TITLE
verify-deployed script should not require same contract list between working git branch and release branch

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#6735]
### Expected Behavior

The verify-deployed script should be able to run without requiring that the working git branch's contract list matches the verified release branch/tag's contract list.  At the very least, if they don't match, it should output a warning.

### Current Behavior

If the contract lists don't match, then verify-deployed script will throw an error.  E.g. I was running the script off of master (commit hash:  26e0d9e80e1e649857e75f9625754297ea33fefb) with the following command:

yarn verify-deployed -n alfajores -b celo-core-contracts-v1.alfajores -f

If failed with the following output:

```
bash-3.2$  yarn verify-deployed -n alfajores -b celo-core-contracts-v1.alfajores -f
yarn run v1.17.3
$ ./scripts/bash/verify-deployed.sh -n alfajores -b celo-core-contracts-v1.alfajores -f
- Checkout source code at celo-core-contracts-v1.alfajores
- Build contract artifacts
- Return to original git commit
Previous HEAD position was da72e7e85 [N13] FixidityLib created as an external library (#5250)
Switched to branch 'master'
- Build verification script
- Run verification script
$ /Users/kevjue/Celo/celo-monorepo/node_modules/.bin/truffle exec ./scripts/truffle/verify-bytecode.js --network alfajores --build_artifacts build/celo-core-contracts-v1.alfajores/contracts --forno
> Warning: possible unsupported (undocumented in help) command line option: --build_artifacts,--forno
Using network 'alfajores'.
Proposal contains only valid release transactions!
Initialization Data was verified!
Contract deployed at 0xa32665e863D7d0d961A21F99bE43393cDeB4B037 matches Validators
Library deployed at 0xd4c090ba41102b7b07fa0801105f419aaf7a7b51 matches AddressLinkedList
TypeError: Cannot read property 'deployedBytecode' of undefined
    at getSourceBytecodeFromArtifacts (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.ts:77:54)
    at getSourceBytecode (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.ts:80:3)
    at /Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.ts:114:26
    at step (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:33:23)
    at Object.next (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:14:53)
    at /Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:4:12)
    at dfsStep (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.ts:88:91)
    at /Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.ts:247:11
    at step (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:33:23)
    at Object.next (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:14:53)
    at fulfilled (/Users/kevjue/Celo/celo-monorepo/packages/protocol/lib/compatibility/verify-bytecode.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.18 (core: 5.1.18)
Node v10.22.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@yorhodes mentioned that the reason for the failure is that by current working git had new contracts _ExchangeEUR_ and _StableTokenEUR_ that Release 1 didn't have.

**Comment by nambrot** [comment]
@yorhodes @kevjue Is this a duplicate of #6615?

**Comment by kevjue** [comment]
Yes, it's a dup of #6615
