### ISSUE TITLE
Deploy cEUR Oracle  activation governance proposal on Mainnet

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6944]
This governance proposal should include:

1. Enable oracle address (this accounts should be funded and under control so they can report)
2. Freeze stableTokenEUR and exchangeEUR

**Comment by aslawson** [comment]
@martinvol will this be at the same time as the contract deployment? and do you plan to test this out with the baklava and alfajores releases as well?
and i'd assume there would be another proposal to unfreeze?

**Comment by asaj** [comment]
@aslawson no it is a follow up, yes we plan to test on the other releases, and yes there needs to be a follow up proposal. This should have been put on the economics board, not the CAP board.

**Comment by martinvol** [comment]
Since last @asaj comment we changed plans and this proposal will be submitted along with CR3.

**Comment by bowd** [comment]
Addresses from mainnet HSMs:
```
mainnet-eur-oracle-weu1 -> 0xeF1E143C554EFC43B0537Af00Ac27C828dE6cF8D
mainnet-eur-oracle-weu2 -> 0xF4B4AA107F30206EA019DE145A9b778a220f9fc0
mainnet-eur-oracle-weu3 -> 0x24c303e6395DD19806F739619960A311764e3F40
mainnet-eur-oracle-weu5 -> 0xDA413875FB45E5905950Bc08a908ebD246Ee6581
mainnet-eur-oracle-weu0 -> 0x87C45738DAd8Dc3D2b1cCe779E0766329cc408C6
mainnet-eur-oracle-wus2 -> 0xb8bDBfdd591a5be5980983A7ba1710a5F46f42B5
mainnet-eur-oracle-wus3 -> 0x929Ad7f2b781CE830014E824CA2eF0b7b8de87C2
mainnet-eur-oracle-wus4 -> 0xCCC0B54edD8dAe3c15b5C002dd5d348495d4f7fe
mainnet-eur-oracle-wus0 -> 0xC5280DDbDEC37540436935C01C912869B2d5Ae1c
mainnet-eur-oracle-wus1 -> 0xBD955F84e11EE53095F9068b88C9d2Ffd3Def707
```

**Comment by martinvol** [comment]
Done https://celo.stake.id/#/proposal/22

**Comment by martinvol** [comment]
Tested the status after the deployment:
```
buckets:0,0
exchanging...
Error: Error: Your request got reverted with the following reason string: can't call when contract is frozen
    at Connection.<anonymous> (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/src/connection.ts:367:13)
    at step (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:44:23)
    at Object.throw (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:25:53)
    at rejected (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:17:65)
✨  Done in 12.46s.
sending...
(node:22306) UnhandledPromiseRejectionWarning: Error: Error: Your request got reverted with the following reason string: can't call when contract is frozen
    at Connection.<anonymous> (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/src/connection.ts:367:13)
    at step (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:44:23)
    at Object.throw (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:25:53)
    at rejected (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:17:65)
(node:22306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Buckets are empty and the contracts frozen!
