### ISSUE TITLE
Test cEUR after oracle activation governance proposal

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#7262]
it should:

1. be frozen (StableToken and ExchangeEUR)
2. oracle addresses should be funded.
3. Oracles should be deployed, reports correct and buckets updated.
4. Bucket sizes should be correct

**Comment by martinvol** [comment]
Transfer is frozen:
```
(node:4047) UnhandledPromiseRejectionWarning: Error: Error: Your request got reverted with the following reason string: can't call when contract is frozen
    at Connection.<anonymous> (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/src/connection.ts:367:13)
    at step (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:44:23)
    at Object.throw (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:25:53)
    at rejected (/Users/martinvol/celo/celo-monorepo/packages/sdk/connect/lib/connection.js:17:65)
(node:4047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

exchange is frozen:
```
buy failed:Error: Error: Your request got reverted with the following reason string: can't call when contract is frozen
sell failed:Error: Error: Your request got reverted with the following reason string: can't call when contract is frozen
```


Buckets snapshots (`exchange.getBuyAndSellBuckets(true))`):
`buckets:5.02469658473134598693237e+23,1.32728335175300366826013e+23`
`buckets:4.82566708851040268590184e+23,1.32731893568148823068828e+23`

Todo: check that the size of the bucket is correct

**Comment by martinvol** [comment]
@sissnad made some manual math and checked that the buckets were indeed consistent!
