### ISSUE TITLE
Fail to build ./packages/protocol

### ISSUE THREAD

**Issue by jon-chuang** [celo-org/celo-monorepo#7355]
### Expected Behavior

Build resulting in `./build`

### Current Behavior

Running `npm install` results in error
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @celo/base@1.0.3-dev.
...
```
Running `yarn run test` results in error
```
Error: Cannot find module 'ts-node/register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/truffle-config.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.require (internal/modules/cjs/helpers.js:25:18)
    at Function.load (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/packages/config/d
ist/index.js:161:1)
    at Function.detect (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/packages/config
/dist/index.js:150:1)
    at Object.run (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/packages/core/lib/co
mmands/compile.js:53:1)
    at Command.run (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/packages/core/lib/c
ommand.js:136:1)
    at Object.<anonymous> (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/packages/cor
e/cli.js:52:1)
    at __webpack_require__ (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/webpack/boo
tstrap 12cfd8a35e0f27e895aa:19:1)
    at /home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/webpack:/webpack/bootstrap 12cfd8a35e0f27
e895aa:62:1
    at Object.<anonymous> (/home/jonch/Desktop/Programming/blockchain/celo-monorepo/packages/protocol/node_modules/truffle/build/cli.bundled.js:68:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by m-chrzan** [comment]
Have you successfully ran `yarn install` in the top level of the monorepo on your currently checked out commit?

**Comment by jon-chuang** [comment]
I tried `npm install`, but I noticed that the `@celo/pkg-name/@ver_num-dev` package versions are not available on npm registry. I either changed to the non `-dev` versions or installed locally. This worked.

Was I supposed to run `npm install` in `packages` rather than in `packages/protocol`?

**Comment by m-chrzan** [comment]
> Was I supposed to run `npm install` in `packages` rather than in `packages/protocol`?

If you're working with a full monrepo checkout, you'll likely need to `yarn install` from the root directory (so not even ` packages/`, but the very root of the repo) before working with individual packages.

**Comment by jon-chuang** [comment]
I see, I will do that in the future, thanks!
