### ISSUE TITLE
governance:build-proposal can't handle big numbers

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7466]
### Expected Behavior

Building the proposal interactively should work

### Current Behavior

build-proposal with GoldToken#approve 15000k CELO failed

```
{ Error: invalid BigNumber string (argument="value", value="1.5e+22", code=INVALID_ARGUMENT, version=bignumber/5.0.15)
    at Logger.makeError (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Logger.throwArgumentError (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
    at Function.BigNumber.from (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:230:27)
    at NumberCoder.encode (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/abi/lib/coders/number.js:30:39)
    at /Users/nambrot/.config/yarn/global/node_modules/@ethersproject/abi/lib/coders/array.js:55:19
    at Array.forEach (<anonymous>)
    at Object.pack (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/abi/lib/coders/array.js:41:12)
    at TupleCoder.encode (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/Users/nambrot/.config/yarn/global/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/Users/nambrot/.config/yarn/global/node_modules/web3-eth-abi/lib/index.js:121:27)
    at /Users/nambrot/.config/yarn/global/node_modules/web3-eth-contract/lib/index.js:439:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/nambrot/.config/yarn/global/node_modules/web3-eth-contract/lib/index.js:438:8)
    at ProposalBuilder.fromWeb3tx (/Users/nambrot/.config/yarn/global/node_modules/@celo/governance/src/proposals.ts:163:15)
    at ProposalBuilder.<anonymous> (/Users/nambrot/.config/yarn/global/node_modules/@celo/governance/src/proposals.ts:240:17)
    at step (/Users/nambrot/.config/yarn/global/node_modules/@celo/governance/lib/proposals.js:33:23)
    at Object.next (/Users/nambrot/.config/yarn/global/node_modules/@celo/governance/lib/proposals.js:14:53)
    at fulfilled (/Users/nambrot/.config/yarn/global/node_modules/@celo/governance/lib/proposals.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '1.5e+22' }
```

**Comment by yorhodes** [comment]
we are checking that these values are indeed `BigNumber` compatible in the builder
https://github.com/celo-org/celo-monorepo/blob/c77edc97141d587e68be0312c769670842de11d7/packages/sdk/governance/src/proposals.ts#L337
it looks like this is in the `CeloTxObject.encodeABI` which is upstream

**Comment by aslawson** [comment]
@nambrot @yorhodes -- is this blocking build-proposal from working? trying to understand the impact and urgency for this fix

**Comment by nambrot** [comment]
IMO this is blocking indeed, I.e I was unable to use `build-proposal` for CGP20 for a simple ERC20 approval from the community fund

**Comment by barbaraliau** [comment]
Possibly related to #6787
