### ISSUE TITLE
celocli governance:build-proposal throws invalid BigNumber string error

### ISSUE THREAD

**Issue by ghost** [celo-org/celo-monorepo#8256]
### Expected Behavior
Would be cool to be able to use celocli governance:build-proposal to build json code for EpochRewards -> setTargetVotingGoldFraction parameter change for CGPs but got this error when choosing a function parameter. 

Not urgent as json file can be created manually. 

### Current Behavior

`celocli governance:build-proposal --output ./cgp_0034.json
Transaction #1:
? Celo Contract: EpochRewards
? EpochRewards Function: setTargetVotingGoldFraction
? value: 600000000000000000000000
Error: invalid BigNumber string (argument="value", value="6e+23", code=INVALID_ARGUMENT, version=bignumber/5.1.1)
    at Logger.makeError (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/logger/lib/index.js:180:21)
    at Logger.throwError (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/logger/lib/index.js:189:20)
    at Logger.throwArgumentError (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/logger/lib/index.js:192:21)
    at Function.BigNumber.from (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/bignumber/lib/bignumber.js:201:27)
    at NumberCoder.encode (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/abi/lib/coders/number.js:30:39)
    at /Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at TupleCoder.encode (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/lib/index.js:121:27)
    at /Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/lib/index.js:439:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/lib/index.js:438:8)
    at ProposalBuilder.fromWeb3tx (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@celo/governance/lib/proposals.js:225:23)
    at ProposalBuilder.<anonymous> (/Users/tobi/.nvm/versions/node/v12.22.1/lib/node_modules/@celo/celocli/node_modules/@celo/governance/lib/proposals.js:316:52) {
  reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '6e+23'`

**Comment by ghost** [comment]
Same error / behaviour for EpochRewards -> setCommunityRewardFraction

**Comment by aslawson** [comment]
Thank @tobikuhlmann - closing this as a duplicate, but will reference this ticket for additional details.
Duplicate #6787
